### ISSUE TITLE
[Question] Disable Invar Block/Nugget/Ingot

### ISSUE THREAD

**Issue by TheSnowyChickens** [Landmaster/PlusTiC#105]
Hello [first , sry for bad english :D]
I have a question about your Invar stuff .

Is it possible to disable your blocks ? Because , I have the CoFH Mods installed and the Thermal F. Invar ingots/blocks/nuggets crafts into your Invar stuff and not back into the Thermal stuff.

This is rly bad for autocrafting I think.
![invar](https://user-images.githubusercontent.com/29357962/30295526-34633148-9741-11e7-9aa4-820b5cb3c977.png)

I hope you know what I mean. xD

Thx

**Comment by Landmaster** [comment]
The invar items are there so that invar can be used as long as there is nickel, even in the absence of a mod that adds invar proper. As long as invar oredicts are handled properly, that should not be a problem.

If that *is* a problem, though, I would recommend you use [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker) to disable the recipes.
