### ISSUE TITLE
[Request] Larger Alloy Ratios

### ISSUE THREAD

**Issue by ZeekDaGeek** [Landmaster/PlusTiC#146]
Would it be possible to increase the alloy ratios by default at the moment some of them are 1mb + 1mb = 2mb which means making alloys takes forever. It's 3.6 seconds to make an ingot with no TPS issues. It's pretty brutal when you need to make thousands of a resource.

**Comment by Landmaster** [comment]
[This is not an issue; standard Tinkers Construct does this the same way (i.e. with the GCD divided out).](https://github.com/SlimeKnights/TinkersConstruct/blob/d67cc3d00074608a4283df801602f21a6ff6da32/src/main/java/slimeknights/tconstruct/smeltery/TinkerSmeltery.java#L530-L537) If you want the alloys to be made faster, use Minetweaker.

**Comment by ZeekDaGeek** [comment]
It is an issue though, every alloy that Tinker's makes you can make in different ways. Also Pig Iron, Obsidian, Knightslime and manyullyn are all in larger ratios. And having the mentality of "this mod does it bad so we should do it bad too" is not a way to improve things. Making it so PlusTiC has an option to do larger ratios of those would be great too.

Any standard alloy that Tinker's can make but another mod can make faster people use the other mods later game, PlusTiC has no higher tech alternatives though.

**Comment by Landmaster** [comment]
Here's the thing:

The alloys that have high ratios are all nonmetallic. The metallic alloys have divided-out ratios *on purpose.* This allows even small fractional parts of metals to be alloyed.

Anyhoo, I'm locking this conversation because claiming that either PlusTiC or Tinkers Construct is doing something badly without giving **solid** evidence does not lead anyone anywhere.
