### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Charismara** [Landmaster/PlusTiC#157]
My Game crash with this mod :(

Here is my crashreport: https://pastebin.com/C8BzGZCh

**Comment by Landmaster** [comment]
Find the smallest set of mods that causes this crash, because it is not evident from the log whether or not the crash is caused by PlusTiC.

**Comment by Charismara** [comment]
Here  the crashreport with minimal mods: https://pastebin.com/abavSqUE

**Comment by Landmaster** [comment]
I tried those minimal mods with the latest versions, but the crash still cannot be reproduced. Did you change anything in the configs?

**Comment by Charismara** [comment]
My Configfiles:
Natura.cfg https://pastebin.com/v59JZ5Su
NaturaModules.cfg https://pastebin.com/xavg5nK6
tconstruct.cfg https://pastebin.com/rTckYJW1
TinkerModules.cfg https://pastebin.com/DvadNLdP
plustic.cfg https://pastebin.com/HTHMPdLW

**Comment by Landmaster** [comment]
Natura.cfg:
>B:"Generate Fusewood Trees"=false
B:"Generate Ghostwood Trees"=false

plustic.cfg:
>B:"Enable material ghostwood_plustic"=true
B:"Enable material fusewood_plustic"=true

And therein lies the problem. Make sure you either enable the trees in question in Natura.cfg, or disable the materials in question in plustic.cfg. Otherwise, PlusTiC will load the materials even if they do not exist.
