### ISSUE TITLE
PlusTiC crashes with a development build of EnderIO

### ISSUE THREAD

**Issue by 343N** [Landmaster/PlusTiC#168]
On minecraft 1.12, PlusTiC seems to crash the game when a developmental build of EnderIO is installed. I'm not sure if this is on the EnderIO dev to fix, but seeing that the crash was caused by PlusTiC I'm reporting it here. Using the latest version of PlusTiC, 6.3.7.0.

Here's the crash report: https://pastebin.com/QUvGfBJ1

**Comment by 343N** [comment]
Disabling EnderIO integration in the PlusTiC config seems to fix the issue.

**Comment by Landmaster** [comment]
EnderIO integration is already disabled by default and deprecated in PlusTiC. It looks like you upgraded from an older version of PlusTiC and the old settings had carried over.

**Comment by Sandriell** [comment]
If support for EnderIO is deprecated, why check for the config option at all? Hardcode it to disabled.

**Comment by Landmaster** [comment]
It already is. The only problem is that old configs do not update to reflect new defaults, which, sadly, I can do nothing about.

In fact, since I have been spammed with ***four*** duplicates of this issue, I will remove EnderIO support entirely next version, since EnderIO already adds it by itself.
