### ISSUE TITLE
Constructs Armory Support Megathread

### ISSUE THREAD

**Issue by Landmaster** [Landmaster/PlusTiC#243]
Feel free to submit and debate ideas concerning ConArm support here.

**Comment by ElDoDoMB** [comment]
Modifier : Fly 
Components : Elytra + Nether Star
- Can only be used on chestplate
- You can fly

**Comment by ElDoDoMB** [comment]
Modifier : Feather Falling
Components : 3x Feather + Ender Eye + Slime Block
- Can only be used on boots
- Reduces damage from falling and damage from ender pearl teleportations.
- Multiple levels

**Comment by ElDoDoMB** [comment]
Modifier : Thorns
Components : 5x Iron Bars
- When a a player or mob physically attacks you, they will take damage from your armor
- Multiple levels

**Comment by Landmaster** [comment]
>Modifier : Fly
Components : Elytra + Nether Star

>Can only be used on chestplate
You can fly

Interesting, though a better solution may be to convince the Constructs Armory devs to add that themselves, since those items are from vanilla.

**Comment by TheSnowyChickens** [comment]
Oh, okay. No diamonds. :D

**Comment by ElDoDoMB** [comment]
Modifier: Jetpack
Components: Jetpack(maybe from simply jetpacks)
- Can only be used on chestplate
- Stores energy
- You can fly using energy
- Multiple levels(lead ---> enderium)

**Comment by ElDoDoMB** [comment]
Material: Enderium
Traits:
1. You will not take damage from the use of enderperls
2. If enderman hit you then he will no longer be able to teleport some time

**Comment by ElDoDoMB** [comment]
Modifier: Flux Pack
Components: Leadstone->Reinforced->Enderium Flux Pack(From Simply Jetpacks)

- Can only be used on chestplate
- Stores energy
- Charges armor and held items
- Multiple levels
- Сombine energy from Modifier "Jetpack"
- Uses energy as durability (if energy is over uses durability)

**Comment by SleepySukima** [comment]
Tough as Nails support for ConArm is much needed. 
Tinker's Survival already does this, but it forces several other severely game altering changes on top. ConArm dev has said that it's up to someone else to do it.
 
Jellied Slime and Wool Armor just need ConArm materials, with the modifier being that they either increase or decrease the temperature by 1.

**Comment by Z-Tunic** [comment]
Modifier: Absorbative | Absorption
Components: Book of Absorption
Mod Origin: Unnatural Absorption

Effect: Grants the Absorption Enchantment, as if you were enchanting it on normal armor. Uses one Modifier Slot and can go up to a maximum rank of V.

Unnatural Absorption is a mod that makes Absorption act like a shield that regens overtime if you avoid taking damage. You can use the Book of Absorption to increase your own Absorption Value and Enchant Armor with the Absorption Enchantment, up to V. These stack together and can even stack further via Potion Effects.

Normally the Absorption Enchantment for Armors won't stack on top of each other but you're able to change that if you mess with the mod's config so you can have a Absorption V set. You can also altar how much absorption it gives as well giving absorption an overall cap and much more.

**Comment by Thunder-Nova** [comment]
Gonna add few mods ideas here since ConArm won't take non vanilla suggestions.
------
Capacitors from various mods providing armor, tools, and weapons capacity depending on their capacitor used:
 - Energy level is only half of the capacitor used.
 - it onlg has 1 level, but can only be upgraded or downgraded by using another capacitor without consuming a modifier. Exemple: Armor has a 2000RF energy storage, giving the armor a 9000RF capacitor based on what said above, will uprage the armor to 4500RF. It acts similar to fortitude modifier.
------
Draconic Evolution to ConArm support
Gotta stay simple, and sticking to traits
Wyvern core:
 - Trait: Shielded: Gives a shield that can recharge using RF energy. Needs a capacitor in inventory or the Capacitor modifier.
Awakened Core
 - Traits: Shielded (same as above) and Dragon skin: Dragon breath won't harm player.
Chaos Core:
 - Trait: Shielded and A Void Dance: (Pun intended) Player won't suffer void damage. Or at least fraction the damage.
Using the upgrade keys as modifiers could be a great touch, but they are 1 level and can be only upgraded costing no modifier with the next tier using somewhat higher then equivalent materials as the draconic evolution counterpart. So unlike lapis luck modifier as example, player must change the materials to upgrade to next tier.
--------
Random Thing
Specter Armor
- Stats same as gold
- Trait: Phantom: Reduce the chance of being hit by 10%. It does stacks with other armor piece. Going up to 40%.

Spector force modifier: both tool and armor modifier: makes player able to hit spirits, mobs killed will have a higher chance to spawn spirits.

Magic Hood: Helmet Modifier: Same as the effect of random things' magic hood
 Uses the magic hood and slimeball as materials.

Divining sight: Accessory modifier for helmet: Player can see all vanilla and tinker ore locations in a 11x11x11 area. Material: Universal divining rod, 2 ardite ingots, and 2 cobalt ingots.

Escape artist: Accessory: Leggings modifier: Acts as escape rope from the mod, but with bonus effect. When command is used player in the nether or end teleports to spawn dealing huge damage to armor. Ability will also have a combat cooldown state timer, if hit, abiltity gets a 30 second cooldown, and a 4 minute cooldown if armor user killed another player. This prevent abuse of pvp players from escaping, while stronger players tries to get to the player. Plus can also benifit sneeky pvp players to kills unsuspecting Escape Artist users, some might get greedy while mining with an armor that can teleport. Materials: Escape rope, ectoplasm, and 2 enderpearls

**Comment by Landmaster** [comment]
I'll close this now that this has been up for 1.5 months already.

**Comment by Z-Tunic** [comment]
I know that this is closed but figure I should mention for the "Modifier: Absorbative | Absorption" idea that I posted...

The actual Natural Absorption mod was updated to 1.12.2 a few hours ago. Figure I let you know in case you were thinking of adding this modifier in.
