### ISSUE TITLE
Mod Compatibility issue with Tinker's Complement and Ex Nihilo Creatio

### ISSUE THREAD

**Issue by Cazadorsniper** [Landmaster/PlusTiC#249]
The Global Traveler trait seems to cause item duplication with TComplement's sledge hammers.

**Comment by Landmaster** [comment]
This is neither a PlusTiC nor a TComplement issue. As [this line](https://github.com/BloodyMods/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/handlers/HandlerHammer.java#L15) shows, this is an Ex Nihilo Creatio issue, fixed by changing `EventPriority.LOWEST` to `EventPriority.LOW`.

**Comment by Landmaster** [comment]
@Cazadorsniper I have done my part to resolve this issue, but Ex Nihilo Creatio needs to [change `EventPriority.LOWEST` to `EventPriority.LOW` in this line](https://github.com/BloodyMods/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/handlers/HandlerHammer.java#L15) to finish the fix for this issue. Can you open an issue there linking to this comment? Thanks.

**Comment by Landmaster** [comment]
BloodyMods/ExNihiloCreatio#144
