### ISSUE TITLE
[Suggestion] Access to "Titanium" Tools if either Galacticraft or Advanced Rocketry is installed?

### ISSUE THREAD

**Issue by Z-Tunic** [Landmaster/PlusTiC#253]
In order to access Titanium Tools you need to have Advanced Rocketry installed, however I use Galacticraft and it has Titanium that you can find normally if you explore the Asteroids Dimension, yet if I want to make Titanium Tools I need to have Advanced Rocketry installed.

Could there be a way to allow Titanium Tools to become available if Plustic detects either one of those mods?

**Comment by Landmaster** [comment]
If I recall correctly, they are balanced differently, and (partly because Advanced Rocketry was one of the first mods supported by PlusTiC and partly because, on an unrelated note, [Galacticraft's licensing is somewhat dubious](https://www.reddit.com/r/feedthebeast/comments/7uoim3/comment/dtme64o/)) I prioritize Advanced Rocketry support over Galacticraft, so the answer is no.
