### ISSUE TITLE
New weapon: Katana

### ISSUE THREAD

**Issue by Landmaster** [Landmaster/PlusTiC#26]
This is currently a work in progress. Feel free to post suggestions concerning this weapon's features here.

**Comment by TheUnderTaker11** [comment]
A cool mechanic might be that you can't have a shield and Katana held at the same time. (Since I'm pretty sure they are supposed to be 2 handed weapons.

**Comment by Landmaster** [comment]
I'm planning for the sword to be very fast (slightly slower than a rapier) and bypass the damage immunity incurred after the target has taken prior damage, increasing the amount of hits per second.

**Comment by Landmaster** [comment]
@TheUnderTaker11 The ban on shield use is something I would consider; I will probably allow only the shuriken to be used in the offhand while the katana is in the mainhand.

**Comment by Arakhor** [comment]
Increased damage against unarmored targets would be a fitting trait in my opinion.

**Comment by Landmaster** [comment]
I have published a beta release (4.3.0.0) that adds the Katana. I will leave this open, however, until any major issues that arise are resolved.

**Comment by Cakx** [comment]
I just tested the Katana, as of now its completly overpowered and renders any other weapon useless. I'm glad you made a config option to disable it. :P
A simple iron katana killed a 50 HP Blackbear in 1 Second just by click spamming him.  The Manylum Katana is even worse. It does way more damage than it shows in the UI(?).  (It even seems like the spammed attacks do full damage?!)

I like the idea of a katana as such and it has the potential to be a nice addition to TiC, but as of now its not even close to be balanced and most likely destroys the whole progression of TiC. 

I guess i would try the following:
Reduce the attack speed and ensure that spammed attacks don't do full damage! 
Reduce the durability!
Reduce the damage!

The Combo System is a nice idea but to be honest, i think it does not work in a balanced way, every fight usally involves multiple strikes so in the end you just have a weapon that gets stronger every strike without any extra effort. At least there should be a cap to the combo bonus or an other condition to get combo increase in the first place. The combo bonus should also decrease alot faster!

It should not be the best weapontype, but an alternative to the others,
It could complement a fast evasion or jump based combat style but as of now you can just cut through hordes of enemies like a hot knife cuts through butter. 

Keep things balanced and keep up the great work with your mod!

**Comment by Landmaster** [comment]
@Cakx The Katana is nerfed in version 4.3.0.1.

**Comment by Cakx** [comment]
I see you did some changes but all in all i think its still the strongest weapon. I compared it to rapiers. (I think rapiers are a little OP as well because a high attack speed is just a killer with the 1.9 combat system)
But the katana is still far superior. Even a wooden one is brutally strong.
The Problem with your Combo System is that it's bonus damage even applies to spam clicked attacks.
According to 1.9 Combat rules, spam clicking should give you a strong damage penalty. But with the katana, every single spam click on an enemy make's it even stronger (stronger than a normal non-spam attack.) And it seems like your bonus damage is not even reduced by the 1.9 spam penalty.
The bonus damage should probably be handled with the damage reduction calculation for spammed attacks. If that's to difficult a massive reduction of the combo bonus damage would probably help.
  
Maybe it would be better if the katana would give you combo bonus **PER KILL** and **not per hit**.

An additional idea would be a per material / per weapon **combo bonus cap** that calculates itself out of the total weapon damage etc. (damage/2=maxComboDamage)
e.g. 5 total weapon damage = 2.5 max combo damage or: 10 total weapon damage = 5 max combo bonus.  

You could also add some variables to the config so that the users could tweak the Katana.

**Comment by Landmaster** [comment]
@Cakx I have published a beta release (4.3.0.2) to nerf the katana even further.

**Comment by Cakx** [comment]
I will do some further testing soon, it felt a little better last time i tried. Per Kill Combo bonus was a great improvement but i guess a little more tweaking can be done. You'll hear from me.

**Comment by Landmaster** [comment]
I'll close this issue for now; report any problems that arise as a separate issue.
